version: '3.8'

services:
  app:
    build:
      context: ./
    working_dir: /opt/app
    depends_on:
      - mongo_db
    links:
      - mongo_db
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      SERVER_ENV: "dev"
      APP_NAME: "server-application"
      command: /opt/app/bin/start_server.sh

  mongo_db:
    container_name: mongo_db
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_DATABASE: 'capstone_db'
      MONGO_INITDB_ROOT_USERNAME: 'capstone'
      MONGO_INITDB_ROOT_PASSWORD: 'C@pst0n3'
    ports:
      - 27017:27017
    volumes:
      - mongo_db:/data/db

volumes:
  mongo_db:
